theme: minima
languageCode: "en-us"


minima:
  skin: dark

header_pages:
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      date: "2017-02-23T10:20:00Z" # This field cannot be empty